version: '3.1'

volumes:
  airflow-volume:

services:

  db:
    container_name: juice-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${JUICE_DB_USER}
      POSTGRES_PASSWORD: ${JUICE_DB_PASSWORD}
      POSTGRES_DB: ${JUICE_DB_NAME}
    ports:
      - '5432:5432'

  api:
    container_name: fastapi
    build: 
      context: .
      dockerfile: ./docker-images/fastapi.dockerfile
    image: fastapi
    restart: always
    environment: 
      JUICE_DB_NAME:
      JUICE_DB_USER:
      JUICE_DB_PASSWORD:
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app/api
      - ./database:/app/database
    working_dir: /app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]
    depends_on:
      - db

  airflow-db:
    container_name: airflow-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - '5433:5432'

  airflow-scheduler:
    container_name: airflow-scheduler
    image: apache/airflow:2.0.0
    restart: always
    environment: 
      AIRFLOW_USERNAME:
      AIRFLOW_EMAIL:
      AIRFLOW_FIRSTNAME:
      AIRFLOW_LASTNAME:
      AIRFLOW_PASSWORD:
      JUICE_DB_NAME: 
      JUICE_DB_USER:
      JUICE_DB_PASSWORD:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/data:/opt/airflow/data
      - ./airflow/setup:/opt/airflow/setup
      - ./database:/opt/airflow/dags/common/database
      - airflow-volume:/opt/airflow
    entrypoint: sh -c
    command: >
      "chmod +x /opt/airflow/setup/init.sh && /opt/airflow/setup/init.sh"
    depends_on: 
      - db
      - airflow-db

  airflow-webserver:
    container_name: airflow-webserver
    image: apache/airflow:2.0.0
    restart: always
    ports:
      - '8080:8080'
    environment: 
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    volumes:
      - airflow-volume:/opt/airflow
    command: webserver -D
    depends_on:
      - airflow-scheduler

