version: '3.1'

services:

  db:
    container_name: juice-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${JUICE_DB_USER}
      POSTGRES_PASSWORD: ${JUICE_DB_PASSWORD}
      POSTGRES_DB: juice
    ports:
      - '5432:5432'
    volumes:
      - ./data:/opt/juice_data

  api:
    container_name: fastapi
    build: 
      context: .
      dockerfile: ./docker-images/fastapi.dockerfile
    image: fastapi
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app/api
      - ./database:/app/database
    working_dir: /app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--reload"]
    depends_on:
      - db

  airflow-db:
    container_name: airflow-postgres
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - '5433:5432'

  airflow-scheduler:
    container_name: airflow-scheduler
    image: apache/airflow:2.0.0
    restart: always
    environment: 
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/data:/opt/airflow/data
    entrypoint: sh -c
    command: >
      "
      airflow db init &&
      airflow users create -u ${AIRFLOW_USERNAME} -e ${AIRFLOW_EMAIL} -f ${AIRFLOW_FIRSTNAME} -l ${AIRFLOW_LASTNAME} -p ${AIRFLOW_PASSWORD} -r Admin &&
      airflow scheduler
      "
    depends_on: 
      - airflow-db

  airflow-webserver:
    container_name: airflow-webserver
    image: apache/airflow:2.0.0
    restart: always
    ports:
      - '8080:8080'
    environment: 
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/data:/opt/airflow/data
    command: webserver
    depends_on:
      - airflow-scheduler